### ISSUE TITLE
[FEATURE REQUEST] logoheader and slider title position

### ISSUE THREAD

**Issue by lrodri** [kai-tub/latex-beamer-pure-minimalistic#47]
If logoheader size is bit big, the red title drops significantly. It's possible put  slider title and log at same height?

Thanks in advance

**Comment by kai-tub** [comment]
Well, I am sure that the issue is not relevant anymore, but if you would still like to get help, please show an example.
From what it sounds like, the image-size should be reduced instead of having both the logo and the title next to each other.
