### ISSUE TITLE
[BUG] Typo in \institute{} @beamertheme-pure-minimalistic-demo.tex

### ISSUE THREAD

**Issue by schaafjs** [kai-tub/latex-beamer-pure-minimalistic#62]
**Describe the bug**
It should probably say \institute{Ins**t**itute name} rather than \institute{Insitute name} in the beamertheme-pure-minimalistic-demo.tex file.
I am very sorry to open an issue for this minor typo but I couldn't get the CI to run on [my fork](https://github.com/schaafjs/latex-beamer-pure-minimalistic) so I figured it would probably be the best option to just report it here.

**To Reproduce**
Go to https://github.com/kai-tub/latex-beamer-pure-minimalistic/blob/master/beamertheme-pure-minimalistic-demo.tex#L43.

**Comment by kai-tub** [comment]
Thanks for the hint!
I think the main CI issue is that you are pushing directly to the `master/main` branch.
This will also try to upload the results to the `wiki`, which again requires a special GitHub `secret` to be set.
But this is just a guess. 
I will fix this issue in a second.

**Comment by kai-tub** [comment]
Or, if you want to become a contributor, you can create a new branch in your fork and open a pull request.
If you open a PR the full CI will also be automatically run.

**Comment by schaafjs** [comment]
> I think the main CI issue is that you are pushing directly to the `master/main` branch.

That seems likely.
> Or, if you want to become a contributor, you can create a new branch in your fork and open a pull request.

Sure, I'll do that right away.
